version: '3.7'

services:
  database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myproject
      MYSQL_USER: admin
      MYSQL_PASSWORD: password